
services:
  postgres:
    image: 'postgres:15.6'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123
      
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


  db-neo4j:
    image: 'neo4j:5.22.0-community-bullseye'
    ports:
      # (http://localhost:7474)
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  mongodb:
    image: 'mongodb/mongodb-community-server:6.0.9-ubi9'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data

